### ISSUE TITLE
Sir, I'm try to fetch language but can not working.pls help

### ISSUE THREAD

**Issue by keangkai** [ssd-tutorials/advanced-search-form#3]
Sir, I'm try to fetch language but can not working.pls help

**Comment by sebastiansulinski** [comment]
What error do you get?

**Comment by keangkai** [comment]
this error 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'languages.name' in 'field list'

in function.php
$sql = "SELECT DISTINCT(`books`.`id`),
            `books`.`title` AS `Title`,
            `books`.`age` AS `Age`,
            `books`.`career` AS `Career`,
            YEAR(`books`.`date_released`) AS Year,
            `books`.`price` AS `Price`,
            `categories`.`name` AS `Category`,
            `languages`.`name` AS `Language`,
            (
                SELECT
                GROUP_CONCAT(`name` ORDER BY `name` ASC SEPARATOR ', ')
                FROM `authors`
                WHERE `id` IN (
                    SELECT `author_id`
                    FROM `books_authors`
                    WHERE `book_id` = `books`.`id`
                )
            ) AS `Author`

           FROM `books`

           JOIN `categories`
                ON `categories`.`id` = `books`.`category`";

in index.php 

<td>
       <?php echo $row['Language']; ?>
 </td>

**Comment by keangkai** [comment]
in index.php

<td>
        <?php echo $row['Language']; ?>
</td>

**Comment by sebastiansulinski** [comment]
Did you add join for the `languages` table?
