### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by ghost** [ssd-tutorials/advanced-search-form#4]
Hi I've a question about the results output. How do I get rid of the automated results? I don't want to have books name when I enter the search function.

I'm using this on a project that I'm working on and don't want the three books to be there as a default.

**Comment by sebastiansulinski** [comment]
In `index.php` make sure that you fetch records only when the request contains the query string i.e.

```php
require_once("inc/config.php");
require_once("inc/functions.php");

$records = [];

if (array_key_exists('keyword', $_GET)) {

    $params = fetchSearch(
        [
            'keyword',
            'category',
            'cover',
            'author',
            'language',
            'year',
            'location'
        ],
        [
            'location'
        ]
    );

    $records = getRecords($params);
}
```

**Comment by ghost** [comment]
Thanks for the help. Another question about the search function. When I press the search button without searching for anything I get the default books up, how do I fix it? I've some very basic PHP skills.

**Comment by sebastiansulinski** [comment]
You can update the conditional statement to:

```php
if (array_key_exists('keyword', $_GET) && $_GET['keyword'] !== '') {
```

**Comment by ghost** [comment]
It all works perfectly but I've one more question, how do I get the pagination which is used on advanced search form php master? I've tried to copy and paste but I coulden't find everything. I know it's old but it dosent work anymore. It gets an error for not finding autopath in vendor.

**Comment by sebastiansulinski** [comment]
I don't think that one is going to work with this code, but try and see if you can make use of this one https://github.com/sebastiansulinski/php-paginator

**Comment by ghost** [comment]
I get an error open it. It says: failed to open stream: No such file or directory. It can't open because it can't find vendor/autoload.php

**Comment by sebastiansulinski** [comment]
Did you install composer dependencies? Make sure you have composer installed first: [https://getcomposer.org/download/](https://getcomposer.org/download/)

You then need to run `composer install` from within your project's directory.
